# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "yoolinkpro-ruby-sdk"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vincent Durand"]
  s.date = "2013-02-14"
  s.description = "YoolinkPro API Ruby SDK, manage your feed, users, groups, teams..."
  s.email = "vincent@yoolink.fr"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/hash_ext.rb",
    "lib/yoolinkpro-ruby-sdk.rb",
    "lib/yoolinkpro/api.rb",
    "lib/yoolinkpro/client.rb",
    "lib/yoolinkpro/exceptions.rb",
    "lib/yoolinkpro/request.rb",
    "spec/hash_ext_spec.rb",
    "spec/spec_helper.rb",
    "spec/yoolinkpro-ruby-sdk_spec.rb",
    "yoolinkpro-ruby-sdk.gemspec"
  ]
  s.homepage = "http://github.com/madwork/yoolinkpro-ruby-sdk"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "YoolinkPro API Ruby SDK"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.7"])
      s.add_runtime_dependency(%q<oj>, ["~> 2.0.4"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.12"])
      s.add_development_dependency(%q<rspec>, ["~> 2.12.0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.9.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<guard>, ["~> 1.6.2"])
      s.add_development_dependency(%q<guard-bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 2.4.0"])
      s.add_development_dependency(%q<rb-inotify>, ["~> 0.9.0"])
    else
      s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
      s.add_dependency(%q<oj>, ["~> 2.0.4"])
      s.add_dependency(%q<activesupport>, ["~> 3.2.12"])
      s.add_dependency(%q<rspec>, ["~> 2.12.0"])
      s.add_dependency(%q<webmock>, ["~> 1.9.0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<guard>, ["~> 1.6.2"])
      s.add_dependency(%q<guard-bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<guard-rspec>, ["~> 2.4.0"])
      s.add_dependency(%q<rb-inotify>, ["~> 0.9.0"])
    end
  else
    s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
    s.add_dependency(%q<oj>, ["~> 2.0.4"])
    s.add_dependency(%q<activesupport>, ["~> 3.2.12"])
    s.add_dependency(%q<rspec>, ["~> 2.12.0"])
    s.add_dependency(%q<webmock>, ["~> 1.9.0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<guard>, ["~> 1.6.2"])
    s.add_dependency(%q<guard-bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<guard-rspec>, ["~> 2.4.0"])
    s.add_dependency(%q<rb-inotify>, ["~> 0.9.0"])
  end
end

