# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yoolinkpro-ruby-sdk}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vincent Durand"]
  s.date = %q{2013-01-22}
  s.description = %q{YoolinkPro API Ruby SDK, manage your feed, users, groups, teams...}
  s.email = %q{vincent@yoolink.fr}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/hash_ext.rb",
    "lib/yoolinkpro-ruby-sdk.rb",
    "lib/yoolinkpro/api.rb",
    "lib/yoolinkpro/client.rb",
    "lib/yoolinkpro/exceptions.rb",
    "spec/hash_ext_spec.rb",
    "spec/spec_helper.rb",
    "spec/yoolinkpro-ruby-sdk_spec.rb",
    "yoolinkpro-ruby-sdk.gemspec"
  ]
  s.homepage = %q{http://github.com/madwork/yoolinkpro-ruby-sdk}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{YoolinkPro API Ruby SDK}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.7"])
      s.add_runtime_dependency(%q<oj>, ["~> 2.0.1"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.11"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<guard>, ["~> 1.6.1"])
      s.add_development_dependency(%q<guard-bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 1.2.1"])
      s.add_development_dependency(%q<rb-inotify>, ["~> 0.8.8"])
    else
      s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
      s.add_dependency(%q<oj>, ["~> 2.0.1"])
      s.add_dependency(%q<activesupport>, ["~> 3.2.11"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<guard>, ["~> 1.6.1"])
      s.add_dependency(%q<guard-bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<guard-rspec>, ["~> 1.2.1"])
      s.add_dependency(%q<rb-inotify>, ["~> 0.8.8"])
    end
  else
    s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
    s.add_dependency(%q<oj>, ["~> 2.0.1"])
    s.add_dependency(%q<activesupport>, ["~> 3.2.11"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<guard>, ["~> 1.6.1"])
    s.add_dependency(%q<guard-bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<guard-rspec>, ["~> 1.2.1"])
    s.add_dependency(%q<rb-inotify>, ["~> 0.8.8"])
  end
end

